var valores = [true, 5, false, "hola", "adios", 2];
var resultado = valores[3] > valores[4];
document.write("El resultado es:"+resultado+"");
var valor1 = valores[0];
var valor2 = valores[2];
var resultado = valor2 ||  valor1;
document.write("<br> El resultado es:"+resultado+"");
resultado = valor2 && valor1;
document.write("<br> El resultado es:"+resultado+"");
var num1 = valores[1];
var num2 = valores[5];
var suma = num1 + num2;
document.write("<br> La suma es:"+suma+"");
var resta = num1 - num2;
document.write("<br> La resta es:"+resta+"");
var multiplicacion = num1 * num2;
document.write("<br> La multiplicacion es:"+multiplicacion+"");
var division = num1 / num2;
document.write("<br> La division es:"+division+"");